### PR TITLE
Replaced __resource to fxmanifest

### PR DESCRIPTION
**Pull request by Tinky124**

### CODE REVIEW

**Review by RedAlex — CHANGES_REQUESTED** [review]
File need to be rename too to fxmanifest.lua

**Comment by Tinky124** [comment]
@RedAlex Sorry i forgot xD here you go

**Comment by RedAlex** [comment]
Thx

**Review by Jbgaming318 — COMMENTED** [review]
changed

**Review by Jbgaming318 — COMMENTED** [review]
changed

**Review by Jbgaming318 — COMMENTED** [review]
changed

**Review by Jbgaming318 — COMMENTED** [review]
changed

**Pull request merged**
